#ifndef BZCONFIG_H
#define BZCONFIG_H

#define IS_PMEM		
#define BZ_DEBUG

#define DESCRIPTOR_POOL_SIZE	512
#define WORD_DESCRIPTOR_SIZE	4
#define CALLBACK_SIZE			4

#define GC_WAIT_MS				10

#define NODE_CONSOLIDATE_SIZE	1024
#define NODE_SPLIT_SIZE			4096
#define NODE_MERGE_SIZE			2048
#define NODE_ALLOC_SIZE			5120

#endif // !BZCONFIG_H
